name: 'Verify service code coverage'

description: 'Verifies that code coverage by tests is noo less than specified threshold'

inputs:
  application-name:
    description: 'Name of the service to verify'
    required: true
  github-token:
    description: 'Github access token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Gradle environment
      uses: ./.github/actions/setup-gradle-env-action

    - name: Download compiled classes and JaCoCo exec
      uses: actions/download-artifact@v4
      with:
        name: build
        path: ${{ github.workspace }}/${{ inputs.application-name }}/build

    - name: Generate JaCoCo reports and verify code coverage
      run: ./gradlew :${{ inputs.application-name }}:jacocoTestReportAndVerification
      shell: bash

    - name: Upload JaCoCo html report
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: jacoco-report
        path: ${{ github.workspace }}/${{ inputs.application-name }}/build/reports/jacoco/test/html
        retention-days: 1

    - name: Add JaCoCo report to PR
      id: jacoco
      if: github.event_name != 'workflow_dispatch'
      uses: madrapps/jacoco-report@v1.6.1
      with:
        paths: ${{ github.workspace }}/${{ inputs.application-name }}/build/reports/jacoco/test/jacocoTestReport.xml
        token: ${{ inputs.github-token }}
        min-coverage-overall: 40
        min-coverage-changed-files: 80
        title: ${{ inputs.application-name }} code coverage
        update-comment: true
        pass-emoji: ✔️
        fail-emoji: ❌

    - name: Add the code coverage info to build summary
      if: github.event_name != 'workflow_dispatch'
      run: .github/scripts/print-test-coverage.sh
      shell: bash

    - name: Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ inputs.github-token }}
        allow-empty: true
#        base-path: ${{ github.workspace }}/${{ inputs.application-name }}
        base-path: ./${{ inputs.application-name }}
