server:
  port: \${PORT:0}

spring:
  application:
    name: app-service-comments
  aop:
    proxy-target-class: false
  profiles:
    active: \${SPRING_ACTIVE_PROFILES:dev}
  sql:
    init:
      platform: postgres
  datasource:
    driverClassName: org.postgresql.Driver
    url: \${JDBC_DATABASE_URL}
    username: \${JDBC_DATABASE_USERNAME}
    password: \${JDBC_DATABASE_PASSWORD}
    hikari:
      auto-commit: false
  flyway:
    url: \${spring.datasource.url}
    user: \${spring.datasource.username}
    password: \${spring.datasource.password}
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0.0
  output:
    ansi:
      enabled: always
  cache:
    caffeine:
      spec: 'initialCapacity=100,maximumSize=500,expireAfterAccess=300s'
  cloud:
    aws:
      credentials:
        access-key: \${AWS_ACCESS_KEY}
        secret-key: \${AWS_SECRET_KEY}
      region:
        static: \${AWS_REGION}

dgs:
  graphql:
    graphiql:
      enabled: false

app-props:
  retry-attempts: 5
  aws:
    sqs:
      user-created-events: \${AWS_SQS_USER_CREATED_EVENTS_FOR_COMMENTS}
      user-deleted-events: \${AWS_SQS_USER_DELETED_EVENTS_FOR_COMMENTS}
      post-created-events: \${AWS_SQS_POST_CREATED_EVENTS_FOR_COMMENTS}
      post-deleted-events: \${AWS_SQS_POST_DELETED_EVENTS_FOR_COMMENTS}

---

spring:
  config:
    activate:
      on-profile: dev
    import:
      - optional:file:${project.rootDir}/.env[.properties]
      - optional:file:${project.rootDir}/../.env[.properties]
  cache:
    caffeine:
      spec: 'initialCapacity=100,maximumSize=500,expireAfterAccess=300s,recordStats'
  devtools:
    livereload:
      enabled: true
      port: 35731
  cloud:
    aws:
      sns:
        endpoint: \${AWS_ENDPOINT}
      sqs:
        endpoint: \${AWS_ENDPOINT}

dgs:
  reload: true
  graphql:
    graphiql:
      enabled: true

tracing:
  method-execution-logging:
    enabled: true
    level: debug
