version: "3.8"

services:

  localstack:
    image: localstack/localstack:1.4.0
    ports:
      - "4566:4566"
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./scripts/localstack:/etc/localstack/init/ready.d/"

  dgs-users-db:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    tmpfs:
      - "/var/lib/postgresql/data"
    env_file:
      - ".env.dev"

  dgs-users-app:
    image: dgs-users-app:latest
    build:
      context: dgs-users
    depends_on:
      - dgs-users-db
      - localstack
    env_file:
      - ".env.dev"
    network_mode: host
    healthcheck:
      test: "curl --fail --silent localhost:5001/api/health | grep UP || exit 1"
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  dgs-topics-db:
    image: postgres:12-alpine
    ports:
      - "5433:5432"
    tmpfs:
      - "/var/lib/postgresql/data"
    env_file:
      - ".env.dev"

  dgs-topics-app:
    image: dgs-topics-app:latest
    build:
      context: dgs-topics
    depends_on:
      - dgs-topics-db
      - localstack
    env_file:
      - ".env.dev"
    network_mode: host
    healthcheck:
      test: "curl --fail --silent localhost:5002/api/health | grep UP || exit 1"
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  dgs-extradata-db:
    image: postgres:12-alpine
    ports:
      - "5434:5432"
    tmpfs:
      - "/var/lib/postgresql/data"
    env_file:
      - ".env.dev"

  dgs-extradata-app:
    image: dgs-extradata-app:latest
    build:
      context: dgs-extradata
    depends_on:
      - dgs-extradata-db
      - localstack
    env_file:
      - ".env.dev"
    network_mode: host
    healthcheck:
      test: "curl --fail --silent localhost:5003/api/health | grep UP || exit 1"
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  apollo-gateway:
    image: apollo-gateway:latest
    build:
      context: apollo-gateway
    depends_on:
      - dgs-users-app
      - dgs-topics-app
      - dgs-extradata-app
    env_file:
      - ".env.dev"
    network_mode: host
