version: "3.8"

services:

  dgs-topics-db:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    tmpfs:
      - "/var/lib/postgresql/data"
    env_file:
      - ".env.dev"

  dgs-users-db:
    image: postgres:12-alpine
    ports:
      - "5433:5432"
    tmpfs:
      - "/var/lib/postgresql/data"
    env_file:
      - ".env.dev"

  dgs-extradata-db:
    image: postgres:12-alpine
    ports:
      - "5434:5432"
    tmpfs:
      - "/var/lib/postgresql/data"
    env_file:
      - ".env.dev"
