version: "3.8"

services:

  localstack:
    image: localstack/localstack:2.1.0
    ports:
      - "127.0.0.1:4566:4566"           # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # ext services port range
      - "127.0.0.1:53:53"               # DNS config
      - "127.0.0.1:53:53/udp"           # DNS config
      - "127.0.0.1:443:443"             # LocalStack HTTPS Gateway
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./scripts/localstack:/etc/localstack/init/ready.d/"
      - "./cloudformation:/cloudformation"

  dgs-users-db:
    image: postgres:12-alpine
    ports:
      - "5501:5432"
    tmpfs:
      - "/var/lib/postgresql/data"
    env_file:
      - "./dgs-users/.env"

  dgs-users-app:
    image: dgs-users-app:latest
    build:
      context: dgs-users
    depends_on:
      - dgs-users-db
      - localstack
    env_file:
      - "./dgs-users/.env"
    network_mode: host
    healthcheck:
      test: "curl --fail --silent localhost:5001/actuator/health | grep UP || exit 1"
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  dgs-posts-db:
    image: postgres:12-alpine
    ports:
      - "5502:5432"
    tmpfs:
      - "/var/lib/postgresql/data"
    env_file:
      - "./dgs-posts/.env"

  dgs-posts-app:
    image: dgs-posts-app:latest
    build:
      context: dgs-posts
    depends_on:
      - dgs-posts-db
      - localstack
    env_file:
      - "./dgs-posts/.env"
    network_mode: host
    healthcheck:
      test: "curl --fail --silent localhost:5002/actuator/health | grep UP || exit 1"
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  dgs-comments-db:
    image: postgres:12-alpine
    ports:
      - "5503:5432"
    tmpfs:
      - "/var/lib/postgresql/data"
    env_file:
      - "./dgs-comments/.env"

  dgs-comments-app:
    image: dgs-comments-app:latest
    build:
      context: dgs-comments
    depends_on:
      - dgs-comments-db
      - localstack
    env_file:
      - "./dgs-comments/.env"
    network_mode: host
    healthcheck:
      test: "curl --fail --silent localhost:5003/actuator/health | grep UP || exit 1"
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  apollo-server:
    image: apollo-server:latest
    build:
      context: apollo-server
    depends_on:
      - dgs-users-app
      - dgs-posts-app
      - dgs-comments-app
    network_mode: host
