includeBuild("lib-platform")
includeBuild("lib-common")
includeBuild("lib-spring-starter-core")
includeBuild("lib-spring-starter-dgs")
includeBuild("lib-spring-starter-security")
includeBuild("lib-spring-starter-tracing")

includeBuild("app-service-users")
includeBuild("app-service-posts")
includeBuild("app-service-comments")
