#!/bin/sh

# **************************************************************************
# *        Script to build and deploy subgraph services for POSIX          *
# **************************************************************************

SKIP_TEST="-Pskip-test"
GRADLE_BUILD_COMMAND=""
DOCKER_BUILD_COMMAND=""

for arg in "$@"
do
    case $arg in
        --test)
            SKIP_TEST=""
            ;;
        --build)
            GRADLE_BUILD_COMMAND="./gradlew :fullBuild"
            DOCKER_BUILD_COMMAND="--build"
            ;;
    esac
done

if [ -n "$GRADLE_BUILD_COMMAND" ]; then
    GRADLE_BUILD_COMMAND="$GRADLE_BUILD_COMMAND $SKIP_TEST &&"
fi

eval "$GRADLE_BUILD_COMMAND docker compose up $DOCKER_BUILD_COMMAND"
