#!/bin/sh

# **************************************************************************
# *        Script to build and deploy subgraph services for POSIX          *
# **************************************************************************

./gradlew :fullBuild -Pskip-test && docker compose up --build
