#!/bin/sh

# **************************************************************************
# *        Script to build and deploy subgraph services for POSIX          *
# **************************************************************************

./gradlew :app-service-users:build :app-service-posts:build :app-service-comments:build &&\
   docker compose up --build
