AWSTemplateFormatVersion: 2010-09-09

Resources:
  # SNS Topics

  UserEventsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: user-events

  PostEventsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: post-events

  # SQS Queues

  UserDeletedEventsForPostsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: user-deleted-events-for-posts

  UserDeletedEventsForCommentsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: user-deleted-events-for-comments

  PostDeletedEventsForCommentsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: post-deleted-events-for-comments

  # SQS Queue Policies

  UserEventsQueuesPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref UserDeletedEventsForPostsQueue
        - !Ref UserDeletedEventsForCommentsQueue
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: '*'
            Action:
              - sqs:SendMessage
            Resource:
              - !GetAtt UserDeletedEventsForPostsQueue.Arn
              - !GetAtt UserDeletedEventsForCommentsQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref UserEventsTopic

  PostEventsQueuesPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref PostDeletedEventsForCommentsQueue
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: '*'
            Action:
              - sqs:SendMessage
            Resource:
              - !GetAtt PostDeletedEventsForCommentsQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref PostEventsTopic

  # SQS -> SNS Subscriptions

  UserDeletedEventsForPostsQueueSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      TopicArn: !Ref UserEventsTopic
      Endpoint: !GetAtt UserDeletedEventsForPostsQueue.Arn
      FilterPolicy:
        x_event_type:
          - UserEvent.Deleted
      RawMessageDelivery: true

  UserDeletedEventsForCommentsQueueSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      TopicArn: !Ref UserEventsTopic
      Endpoint: !GetAtt UserDeletedEventsForCommentsQueue.Arn
      FilterPolicy:
        x_event_type:
          - UserEvent.Deleted
      RawMessageDelivery: true

  PostDeletedEventsForCommentsQueueSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      TopicArn: !Ref PostEventsTopic
      Endpoint: !GetAtt PostDeletedEventsForCommentsQueue.Arn
      FilterPolicy:
        x_event_type:
          - PostEvent.Deleted
      RawMessageDelivery: true
