name: Build & Code Coverage Verification

on:
  workflow_call:
    inputs:
      APP_SERVICE_NAME:
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: gradle

      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build service
        run: ./gradlew :${{ inputs.APP_SERVICE_NAME }}:buildNeeded

      - name: Upload compiled classes and JaCoCo exec
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            ${{ github.workspace }}/${{ inputs.APP_SERVICE_NAME }}/build/classes
            ${{ github.workspace }}/${{ inputs.APP_SERVICE_NAME }}/build/jacoco
          retention-days: 1

  verify-code-coverage:
    name: Code Coverage Verification
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Download compiled classes and JaCoCo exec
        uses: actions/download-artifact@v4
        with:
          name: build
          path: ${{ github.workspace }}/${{ inputs.APP_SERVICE_NAME }}/build

      - name: Generate JaCoCo reports and verify code coverage
        run: ./gradlew :${{ inputs.APP_SERVICE_NAME }}:jacocoTestReportAndVerification

      - name: Upload JaCoCo html report
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: jacoco-report
          path: ${{ github.workspace }}/${{ inputs.APP_SERVICE_NAME }}/build/reports/jacoco/test/html
          retention-days: 1

      - name: Add JaCoCo report to PR
        id: jacoco
        if: github.event_name != 'workflow_dispatch'
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: ${{ github.workspace }}/${{ inputs.APP_SERVICE_NAME }}/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 80
          title: ${{ inputs.APP_SERVICE_NAME }} code coverage
          update-comment: true
          pass-emoji: ✔️
          fail-emoji: ❌

      - name: Add the code coverage info to build summary
        if: github.event_name != 'workflow_dispatch'
        run: .github/scripts/print-test-coverage.sh
        shell: bash
