name: 'Build service'

description: 'Builds specified service'

inputs:
  application-name:
    description: 'Name of the service to build'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Gradle environment
      uses: ./.github/actions/setup-gradle-env-action

    - name: Build service
      run: ./gradlew :${{ inputs.application-name }}:buildNeeded
      shell: bash

    - name: Upload compiled classes and JaCoCo exec
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: |
          ${{ github.workspace }}/${{ inputs.application-name }}/build/classes
          ${{ github.workspace }}/${{ inputs.application-name }}/build/jacoco
        retention-days: 1
