name: 'Setup Gradle'

description: 'Prepares environment for Gradle usage'

runs:
  using: 'composite'
  steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'
        cache: gradle

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
