name: Comments service CI

on:
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/app-service-comments-CI.yml'
      - '.github/actions/build-and-verify-code-coverage.yml'
      - 'app-service-comments/**'
      - 'lib-*/**'
  pull_request:
    branches:
      - 'master'
    paths:
      - '.github/workflows/app-service-comments-CI.yml'
      - '.github/actions/build-and-verify-code-coverage.yml'
      - 'app-service-comments/**'
      - 'lib-*/**'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build service
        uses: ./.github/actions/build-service-action
        with:
          application-name: 'app-service-comments'

  verify-code-coverage:
    name: Code Coverage Verification
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify code coverage
        uses: ./.github/actions/verify-code-coverage-action
        with:
          application-name: 'app-service-comments'
