name: Scheduled Events service CI

on:
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/app-service-scheduled-events-CI.yml'
      - '.github/workflows/build-and-verify-code-coverage.yml'
      - 'app-service-scheduled-events/**'
      - 'lib-*/**'
  pull_request:
    branches:
      - 'master'
    paths:
      - '.github/workflows/app-service-scheduled-events-CI.yml'
      - '.github/workflows/build-and-verify-code-coverage.yml'
      - 'app-service-scheduled-events/**'
      - 'lib-*/**'
  workflow_dispatch:

jobs:
  test_and_build:
    name: Test and Build
    uses: ./.github/workflows/build-and-verify-code-coverage.yml
    with:
      APP_SERVICE_NAME: 'app-service-scheduled-events'
