name: Scheduled Tasks service CI

on:
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/app-service-scheduled-tasks-CI.yml'
      - 'app-service-scheduled-tasks/**'
      - 'lib-*/**'
  pull_request:
    branches:
      - 'master'
    paths:
      - '.github/workflows/app-service-scheduled-tasks-CI.yml'
      - 'app-service-scheduled-tasks/**'
      - 'lib-*/**'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: gradle

      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build Scheduled Tasks service
        run: './gradlew :app-service-scheduled-tasks:buildNeeded'

      - name: Upload compiled classes and JaCoCo exec
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            ${{ github.workspace }}/app-service-scheduled-tasks/build/classes
            ${{ github.workspace }}/app-service-scheduled-tasks/build/jacoco
          retention-days: 1

  code-coverage:
    name: Code Coverage Verification
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Download compiled classes and JaCoCo exec
        uses: actions/download-artifact@v4
        with:
          name: build
          path: ${{ github.workspace }}/app-service-scheduled-tasks/build

      - name: Generate JaCoCo reports and verify code coverage
        run: './gradlew :app-service-scheduled-tasks:jacocoTestReportAndVerification'

      - name: Upload JaCoCo html report
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: jacoco-report
          path: ${{ github.workspace }}/app-service-scheduled-tasks/build/reports/jacoco/test/html
          retention-days: 1

      - name: Add JaCoCo report to PR
        id: jacoco
        if: github.event_name != 'workflow_dispatch'
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: ${{ github.workspace }}/app-service-scheduled-tasks/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 80
          title: app-service-scheduled-tasks code coverage
          update-comment: true
          pass-emoji: ✔️
          fail-emoji: ❌

      - name: Add the code coverage info to build summary
        if: github.event_name != 'workflow_dispatch'
        run: .github/scripts/print-test-coverage.sh
        shell: bash
