name: Posts service CI

on:
  push:
    branches:
      - 'master'
    paths:
      - 'app-service-posts/**'
      - 'lib-common/**'
      - 'lib-platform/**'
      - 'lib-spring-starter-config/**'
      - 'lib-spring-starter-dgs/**'
      - 'lib-spring-starter-security/**'
      - 'lib-spring-starter-tracing/**'
  pull_request:
    branches:
      - 'master'
    paths:
      - 'app-service-posts/**'
      - 'lib-common/**'
      - 'lib-platform/**'
      - 'lib-spring-starter-config/**'
      - 'lib-spring-starter-dgs/**'
      - 'lib-spring-starter-security/**'
      - 'lib-spring-starter-tracing/**'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper

      - name: Build Posts service
        run: 'gradle :app-service-posts:build'
