name: Users service CI

on:
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/app-service-users-CI.yml'
      - 'app-service-users/**'
      - 'lib-common/**'
      - 'lib-platform/**'
      - 'lib-spring-starter-config/**'
      - 'lib-spring-starter-dgs/**'
      - 'lib-spring-starter-security/**'
      - 'lib-spring-starter-tracing/**'
  pull_request:
    branches:
      - 'master'
    paths:
      - '.github/workflows/app-service-users-CI.yml'
      - 'app-service-users/**'
      - 'lib-common/**'
      - 'lib-platform/**'
      - 'lib-spring-starter-config/**'
      - 'lib-spring-starter-dgs/**'
      - 'lib-spring-starter-security/**'
      - 'lib-spring-starter-tracing/**'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3-beta
        with:
          gradle-version: wrapper

      - name: Build Users service
        run: './gradlew :app-service-users:build'

      - name: Add JaCoCo report to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: ${{ github.workspace }}/app-service-users/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 80
          title: app-service-users code coverage
          update-comment: true
          pass-emoji: ✔️
          fail-emoji: ❌

      - name: Add the code coverage info to build summary
        run: |
          echo "### JaCoCo Test Coverage Summary"                                        >> $GITHUB_STEP_SUMMARY
          echo "|     Type      |                      Coverage                       |" >> $GITHUB_STEP_SUMMARY
          echo "|---------------|-----------------------------------------------------|" >> $GITHUB_STEP_SUMMARY
          echo "| Overall files | ${{ steps.jacoco.outputs.coverage-overall }}%       |" >> $GITHUB_STEP_SUMMARY
          echo "| Changed files | ${{ steps.jacoco.outputs.coverage-changed-files }}% |" >> $GITHUB_STEP_SUMMARY
          echo "---"                                                                     >> $GITHUB_STEP_SUMMARY

  code-coverage:
    name: Code Coverage Verification
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3-beta
        with:
          gradle-version: wrapper

      - name: Generate JaCoCo Report
        run: 'gradle :app-service-users:jacocoTestReport'