name: Comments service CI

env:
  APPLICATION_NAME: 'app-service-comments'

on:
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/${{ env.APPLICATION_NAME }}-CI.yml'
      - '.github/actions/**'
      - '${{ env.APPLICATION_NAME }}/**'
      - 'lib-*/**'
  pull_request:
    branches:
      - 'master'
    paths:
      - '.github/workflows/${{ env.APPLICATION_NAME }}-CI.yml'
      - '.github/actions/**'
      - '${{ env.APPLICATION_NAME }}/**'
      - 'lib-*/**'
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and Test
    uses: ./.github/workflows/build-and-verify-code-coverage.yml
    with:
      application-name: ${{ env.APPLICATION_NAME }}
