name: Build and verify code coverage

on:
  workflow_call:
    inputs:
      application-name:
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build service
        uses: ./.github/actions/build-service-action
        with:
          application-name: ${{ inputs.application-name }}

  verify-code-coverage:
    name: Code Coverage Verification
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify code coverage
        uses: ./.github/actions/verify-code-coverage-action
        with:
          application-name: ${{ inputs.application-name }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
