name: DGS Posts service CI

on:
  push:
    branches:
      - 'master'
    paths:
      - 'dgs-posts/**'
      - 'shared-bom/**'
      - 'shared-lib/**'
  pull_request:
    branches:
      - 'master'
    paths:
      - 'dgs-posts/**'
      - 'shared-bom/**'
      - 'shared-lib/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: './dgs-posts'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.2.1

      - name: Build DGS Posts service
        run: 'gradle :build'
