name: DGS Users service CI

on:
  push:
    branches:
      - 'master'
    paths:
      - 'services/dgs-users/**'
      - 'services/shared-bom/**'
      - 'services/shared-lib/**'
  pull_request:
    branches:
      - 'master'
    paths:
      - 'services/dgs-users/**'
      - 'services/shared-bom/**'
      - 'services/shared-lib/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: './services/dgs-users'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.2.1

      - name: Build DGS Users service
        run: 'gradle :build'
